- name: Playbook for Integration and deployment the app
  hosts: webserver
  become: true
  vars: 
   repopath: https://github.com/gowthamkarmegam/DevOpsCodeDemo.git
   dest_path: /tmp/projectcode
  tasks: 
   - name: Clone the repo from Github which has the code to worker nodes
     git: repo={{repopath}} dest={{dest_path}}
   - name: Execute maven to build the code
     command: chdir={{dest_path}} mvn package
   - name: copy the artifact from the target folder to current directory
     copy: src=/tmp/projectcode/target/addressbook.war dest={{dest_path}} remote_src=yes
   - name: Build the docker file
     command: chdir={{dest_path}} docker build -t ansibleimage .
   - name: Run the image and deploy the app on the container
     command: docker run -d -P ansibleimage
