- name: Install Maven and Docker on Workder Nodes
  hosts: webserver
  become: true
  tasks: 
   - name: Update apt-get on the Worker Nodes
     command: sudo apt-get update
   - name: Install Maven
     package: name=maven state=present
   - name: Install Docker
     package: name=docker-ce state=present
   - name: Start the Docker
     service: name=docker state=started
